{
  "openapi": "3.0.1",
  "info": {
    "version": "2.0.2",
    "title": "Wallet-API"
  },
  "consumes": ["application/json"],
  "produces": ["application/json"],
  "servers": [
    { "url": "http://localhost:3000" },
    { "url": "https://wallet-back.herokuapp.com" }
  ],
  "tags": [
    {
      "name": "Users",
      "description": "Users endpoints"
    },
    {
      "name": "Transactions",
      "description": "Transactions endpoints"
    }
  ],

  "paths": {
    "/api/users/signup": {
      "post": {
        "tags": ["Users"],
        "summary": "User registration",
        "parameters": [],
        "requestBody": {
          "description": "Registration's object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/RegistrationRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Created",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse201"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response400"
                }
              }
            }
          },
          "400 ": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse400 "
                }
              }
            }
          },
          "409": {
            "description": "Conflic",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/RegistrationResponse409"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/login": {
      "post": {
        "tags": ["Users"],
        "summary": "User login",
        "parameters": [],
        "requestBody": {
          "description": "Login object",
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/LoginRequest"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse201"
                }
              }
            }
          },
          "400": {
            "description": "Bad request",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/Response400"
                }
              }
            }
          },
          "401": {
            "description": "Email or password is wrong",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LoginResponse401"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/logot": {
      "post": {
        "tags": ["Users"],
        "summary": "User logout",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "204": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/LogoutResponse204"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthResponse401"
                }
              }
            }
          }
        }
      }
    },
    "/api/users/current": {
      "get": {
        "tags": ["Users"],
        "summary": "User`s current data",
        "parameters": [],
        "security": [{ "Bearer": [] }],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/CurrentResponse200"
                }
              }
            }
          },
          "401": {
            "description": "Not authorized",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/AuthResponse401"
                }
              }
            }
          }
        }
      }
    }
  },

  "components": {
    "schemas": {
      "RegistrationRequest": {
        "type": "object",
        "required": ["email", "password", "repeated_password", "name"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "repeated_password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          },
          "name": {
            "type": "string",
            "description": "User's name",
            "example": "Elon Musk"
          }
        }
      },
      "RegistrationResponse201": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "name": {
              "type": "string",
              "description": "User's name",
              "example": "Elon Musk"
            }
          }
        },
        "example": {
          "Status": "201 Created",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "New user created",
            "user": {
              "name": "Elon Musk",
              "email": "user@example.com"
            }
          }
        }
      },
      "Response400": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "ResponseBody": {
              "message": "Validation error"
            }
          }
        },
        "example": {
          "Status": "400 Bad Request",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "Validation error"
          }
        }
      },
      "RegistrationResponse400 ": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "ResponseBody": {
              "message": "Entered passwords do not match"
            }
          }
        },
        "example": {
          "Status": "400 Bad Request",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "Entered passwords do not match"
          }
        }
      },
      "RegistrationResponse409": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "ResponseBody": {
              "message": "Email in use"
            }
          }
        },
        "example": {
          "Status": "409 Conflic",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "Email in use"
          }
        }
      },

      "LoginRequest": {
        "type": "object",
        "required": ["email", "password"],
        "properties": {
          "email": {
            "type": "string",
            "description": "User's email",
            "format": "email",
            "example": "user@example.com"
          },
          "password": {
            "type": "string",
            "description": "User's password",
            "example": "qwerty123"
          }
        }
      },
      "LoginResponse201": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "token": {
              "type": "string",
              "description": "User's token"
            },
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "name": {
              "type": "string",
              "description": "User's name",
              "example": "Elon Musk"
            }
          }
        },
        "example": {
          "Status": "201 OK",
          "Content-Type": "application/json",
          "ResponseBody": {
            "token": "token",
            "user": {
              "name": "Elon Musk",
              "email": "user@example.com"
            }
          }
        }
      },
      "LoginResponse401": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "ResponseBody": {
              "message": "Email or password is wrong"
            }
          }
        },
        "example": {
          "Status": "401 Unauthorized",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "Email or password is wrong"
          }
        }
      },
      "LogoutResponse204": {
        "example": {
          "Status": "204 OK"
        }
      },
      "AuthResponse401": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "ResponseBody": {
              "message": "Not authorized"
            }
          }
        },
        "example": {
          "Status": "401 Unauthorized",
          "Content-Type": "application/json",
          "ResponseBody": {
            "message": "Not authorized"
          }
        }
      },
      "CurrentResponse200": {
        "type": "object",
        "items": {
          "type": "object",
          "properties": {
            "email": {
              "type": "string",
              "description": "User's email",
              "format": "email"
            },
            "name": {
              "type": "string",
              "description": "User's name",
              "example": "Elon Musk"
            }
          }
        },
        "example": {
          "Status": "200 OK",
          "Content-Type": "application/json",
          "ResponseBody": {
            "user": {
              "name": "Elon Musk",
              "email": "user@example.com"
            }
          }
        }
      }
    },
    "securitySchemes": {
      "Bearer": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}
